### ISSUE TITLE
Missing argument error (for rv_generic.interval()) when running stats.categorical

### ISSUE THREAD

**Issue by AlistairCurd** [KatherLab/marugoto#14]
Hi,
I ran marugoto.stats.categorical on my predictions after a 5-fold cross-validation:
`python -m marugoto.stats.categorical ./fold-*/patient-preds.csv --outpath ./stats --target-label Diagnosis`

I got this error and traceback:
Traceback (most recent call last):

  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,

  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)

  File "/home/fbsacu/venvs/attmil/lib/python3.10/site-packages/marugoto/stats/categorical.py", line 117, in <module>
    Fire(categorical_aggregated_)

  File "/home/fbsacu/venvs/attmil/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)

  File "/home/fbsacu/venvs/attmil/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(

  File "/home/fbsacu/venvs/attmil/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)

  File "/home/fbsacu/venvs/attmil/lib/python3.10/site-packages/marugoto/stats/categorical.py", line 103, in categorical_aggregated_
    stats_df = aggregate_categorical_stats(preds_df.reset_index())

  File "/home/fbsacu/venvs/attmil/lib/python3.10/site-packages/marugoto/stats/categorical.py", line 71, in aggregate_categorical_stats
    l, h = st.t.interval(alpha=0.95, df=len(scores_df) - 1, loc=means, scale=sems)

TypeError: rv_generic.interval() missing 1 required positional argument: 'confidence'

**Comment by cagankpln** [comment]
I got the same error and it resolved when I changed “alpha” parameter to “confidence” in “marugoto/stats/categorical.py” line 71.

**Comment by Avic3nna** [comment]
@cagankpln @AlistairCurd thank you for pointing this out! For a more user-friendly experience, consider our latest protocol (which includes a comprehensive step-by-step paper for usage):

https://github.com/KatherLab/STAMP
